version: "3.5"

services:
  webserver:
    image: gartz/snake-js
    domainname: gartz.com.br
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 20s
        monitor: 60s
        failure_action: rollback
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.10'
          memory: 15M
